feat(workflow): add configuration validation workflow

diff --git a/.github/workflows/validate-config.yml b/.github/workflows/validate-config.yml
--- a/.github/workflows/validate-config.yml
+++ b/.github/workflows/validate-config.yml
@@ -16,111 +16,111 @@ jobs:
 
       - name: Get config.yml files
         run: |
-          #!/bin/bash
+            #!/bin/bash
 
-          # Define color codes
-          RED='\033[0;31m'
-          GREEN='\033[0;32m'
-          CYAN='\033[0;36m'
-          NC='\033[0m' # No Color
-          ITALIC='\033[3m'
-          BOLD='\033[1m'
-          YELLOW='\033[1;33m'
-          LIGHT_GREEN='\033[1;32m'
-          LIGHT_RED='\033[1;31m'
-          MAGENTA='\033[0;35m'
-          BLUE='\033[0;34m'
+            # Define color codes
+            RED='\033[0;31m'
+            GREEN='\033[0;32m'
+            CYAN='\033[0;36m'
+            NC='\033[0m' # No Color
+            ITALIC='\033[3m'
+            BOLD='\033[1m'
+            YELLOW='\033[1;33m'
+            LIGHT_GREEN='\033[1;32m'
+            LIGHT_RED='\033[1;31m'
+            MAGENTA='\033[0;35m'
+            BLUE='\033[0;34m'
 
-          counter=0
-          total_files=0
-          fail_count=0
+            counter=0
+            total_files=0
+            fail_count=0
 
-          echo -e "\n${BOLD}Hello from ${CYAN}${BOLD}validate-config.yml!${NC} \xF0\x9F\x91\x8B \n"
-          echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"
+            echo -e "\n${BOLD}Hello from ${CYAN}${BOLD}validate-config.yml!${NC} \xF0\x9F\x91\x8B \n"
+            echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"
 
-          echo -e "🚀 ${YELLOW}${BOLD}[Step 1]: ${NC}${BOLD}Running ${LIGHT_GREEN}${ITALIC}${BOLD}validation script${NC} 🔄"
-          echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n"
+            echo -e "🚀 ${YELLOW}${BOLD}[Step 1]: ${NC}${BOLD}Running ${LIGHT_GREEN}${ITALIC}${BOLD}validation script${NC} 🔄"
+            echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n"
 
-          # Debug: Show current directory
-          #echo -e "Current directory: $(pwd)\n"
+            # Debug: Show current directory
+            #echo -e "Current directory: $(pwd)\n"
 
-          root=$(pwd)
+            root=$(pwd)
 
-          #TESTING
-          grep -rl "ghcr.io/liatrio/liatrio-otel-collector" $root_dir > files_collector.txt
+            #TESTING
+            grep -rl "ghcr.io/liatrio/liatrio-otel-collector" $root_dir > files_collector.txt
 
-          while read -r line; do
-                  if [[ $line == *"ghcr.io/liatrio/liatrio-otel-collector"* ]]; then
-                      version=$(echo "$line" | awk -F':' '{print $3}')
-                      echo -e "🔍 ${ITALIC}Found Image Version: ${MAGENTA}${ITALIC}$version 🔧${NC}\n"
-                      break
-                  fi
-          done < files_collector.txt
+            while read -r line; do
+                    if [[ $line == *"ghcr.io/liatrio/liatrio-otel-collector"* ]]; then
+                        version=$(echo "$line" | awk -F':' '{print $3}')
+                        echo -e "🔍 ${ITALIC}Found Image Version: ${MAGENTA}${ITALIC}$version 🔧${NC}\n"
+                        break
+                    fi
+            done < files_collector.txt
 
-          # Find colconfig.yaml files
-          find . -name "colconfig.yaml" > files.txt
+            # Find colconfig.yaml files
+            find . -name "colconfig.yaml" > files.txt
 
-          # Debug: Show contents of files.txt
-          echo -e "${BOLD}Files found:${NC}\n$(cat files.txt)\n"
+            # Debug: Show contents of files.txt
+            echo -e "${BOLD}Files found:${NC}\n$(cat files.txt)\n"
 
-          # Get the total number of config files
-          while read -r line; do
-              total_files=$((total_files+1))
-          done < files.txt
-
-
-
-          while read -r line; do
-
-              #increment counter
-              counter=$((counter+1))
-
-              dir=$(dirname "$line") # Get the config directory
-
-              echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"
-              echo -e "${CYAN}${BOLD}[${YELLOW}$counter${NC}${CYAN}/${YELLOW}$total_files${NC}${CYAN}]${NC} 🧪 ${YELLOW}${ITALIC}$dir/config.yaml${NC}"
-              echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"
-
-              root_dir="${dir%/*/*}" # Get the root directory
-
-              #DEBUG
-              echo -e "📤 ${ITALIC}Extracted Root Directory: ${CYAN}${ITALIC}$root_dir${NC} 🔧"
-
-              file_with_image=$(grep -rl "ghcr.io/liatrio/liatrio-otel-collector" $root_dir)
-
-              #DEBUG
-              echo -e "📁 ${ITALIC}Files containing the specified image reference: 🔧\n     ${BLUE}${ITALIC}$file_with_image${NC}\n"
-
-              while read -r line; do
-                  if [[ $line == *"ghcr.io/liatrio/liatrio-otel-collector"* ]]; then
-                      version=$(echo "$line" | awk -F':' '{print $3}')
-                      echo -e "🔍 ${ITALIC}Found Image Version: ${MAGENTA}${ITALIC}$version 🔧${NC}\n"
-                      break
-                  fi
-              done < "$file_with_image"
-
-              cd $dir #Move into the config directory
-
-              output=$(docker run -v $(pwd):/config ghcr.io/liatrio/liatrio-otel-collector:$version validate --config /config/colconfig.yaml 2>&1 || true)
-              if echo "$output" | grep -q "Error:"; then
-                  echo -e "❌ ${BOLD}Validation ${LIGHT_RED}${BOLD}${ITALIC}failed${NC}"
-                  echo -e "${ITALIC}${output}"
-                  fail_count=$((fail_count+1))
-
-              else
-                echo -e "✅ ${BOLD}Validation ${LIGHT_GREEN}${BOLD}${ITALIC}succeeded${NC}"
-
-              fi
-              cd $root
-          done < files.txt
-
-          echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n"
+            # Get the total number of config files
+            while read -r line; do
+                total_files=$((total_files+1))
+            done < files.txt
 
 
-          if((counter>0)); then
-              echo -e "🚨 ${NC}${BOLD}Validation ${LIGHT_RED}${BOLD}${ITALIC}failed ${NC}${BOLD}for ${LIGHT_RED}${BOLD}${ITALIC}$fail_count${NC}${BOLD}/$total_files configurations! 🚨\n"
-              exit 1
-          else
-              echo -e "✅ ${BOLD}All configurations are ${LIGHT_GREEN}${BOLD}${ITALIC}valid! 🎉\n"
-          fi
-          exit 0
+
+            while read -r line; do
+
+                #increment counter
+                counter=$((counter+1))
+
+                dir=$(dirname "$line") # Get the config directory
+
+                echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"
+                echo -e "${CYAN}${BOLD}[${YELLOW}$counter${NC}${CYAN}/${YELLOW}$total_files${NC}${CYAN}]${NC} 🧪 ${YELLOW}${ITALIC}$dir/config.yaml${NC}"
+                echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖"
+
+                root_dir="${dir%/*/*}" # Get the root directory
+
+                #DEBUG
+                echo -e "📤 ${ITALIC}Extracted Root Directory: ${CYAN}${ITALIC}$root_dir${NC} 🔧"
+
+                file_with_image=$(grep -rl "ghcr.io/liatrio/liatrio-otel-collector" $root_dir)
+
+                #DEBUG
+                echo -e "📁 ${ITALIC}Files containing the specified image reference: 🔧\n     ${BLUE}${ITALIC}$file_with_image${NC}\n"
+
+                while read -r line; do
+                    if [[ $line == *"ghcr.io/liatrio/liatrio-otel-collector"* ]]; then
+                        version=$(echo "$line" | awk -F':' '{print $3}')
+                        echo -e "🔍 ${ITALIC}Found Image Version: ${MAGENTA}${ITALIC}$version 🔧${NC}\n"
+                        break
+                    fi
+                done < "$file_with_image"
+
+                cd $dir #Move into the config directory
+
+                output=$(docker run -v $(pwd):/config ghcr.io/liatrio/liatrio-otel-collector:$version validate --config /config/colconfig.yaml 2>&1 || true)
+                if echo "$output" | grep -q "Error:"; then
+                    echo -e "❌ ${BOLD}Validation ${LIGHT_RED}${BOLD}${ITALIC}failed${NC}"
+                    echo -e "${ITALIC}${output}"
+                    fail_count=$((fail_count+1))
+
+                else
+                  echo -e "✅ ${BOLD}Validation ${LIGHT_GREEN}${BOLD}${ITALIC}succeeded${NC}"
+
+                fi
+                cd $root
+            done < files.txt
+
+            echo -e "➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n"
+
+
+            if((counter>0)); then
+                echo -e "🚨 ${NC}${BOLD}Validation ${LIGHT_RED}${BOLD}${ITALIC}failed ${NC}${BOLD}for ${LIGHT_RED}${BOLD}${ITALIC}$fail_count${NC}${BOLD}/$total_files configurations! 🚨\n"
+                exit 1
+            else
+                echo -e "✅ ${BOLD}All configurations are ${LIGHT_GREEN}${BOLD}${ITALIC}valid! 🎉\n"
+            fi
+            exit 0
